Repository googleapis/python-tasks, pull requests merged in 2021-03, with the labels that each got.

#51 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, samples

#77 chore: remove obsolete block in synth.py
  synth.py
Labels: api: cloudtasks, automerge, cla: yes

#75 test: install pyopenssl for mtls testing
  noxfile.py
  synth.metadata
Labels: api: cloudtasks, cla: yes, context: full

#80 feat: add `from_service_account_info`
  google/cloud/tasks_v2/services/cloud_tasks/async_client.py
  google/cloud/tasks_v2/services/cloud_tasks/client.py
  google/cloud/tasks_v2/services/cloud_tasks/transports/base.py
  google/cloud/tasks_v2/services/cloud_tasks/transports/grpc.py
  google/cloud/tasks_v2/services/cloud_tasks/transports/grpc_asyncio.py
  google/cloud/tasks_v2/types/__init__.py
  google/cloud/tasks_v2beta2/services/cloud_tasks/async_client.py
  google/cloud/tasks_v2beta2/services/cloud_tasks/client.py
  google/cloud/tasks_v2beta2/services/cloud_tasks/transports/base.py
  google/cloud/tasks_v2beta2/services/cloud_tasks/transports/grpc.py
  google/cloud/tasks_v2beta2/services/cloud_tasks/transports/grpc_asyncio.py
  google/cloud/tasks_v2beta2/types/__init__.py
  google/cloud/tasks_v2beta3/services/cloud_tasks/async_client.py
  google/cloud/tasks_v2beta3/services/cloud_tasks/client.py
  google/cloud/tasks_v2beta3/services/cloud_tasks/transports/base.py
  google/cloud/tasks_v2beta3/services/cloud_tasks/transports/grpc.py
  google/cloud/tasks_v2beta3/services/cloud_tasks/transports/grpc_asyncio.py
  google/cloud/tasks_v2beta3/types/__init__.py
  synth.metadata
  tests/unit/gapic/tasks_v2/__init__.py
  tests/unit/gapic/tasks_v2/test_cloud_tasks.py
  tests/unit/gapic/tasks_v2beta2/__init__.py
  tests/unit/gapic/tasks_v2beta2/test_cloud_tasks.py
  tests/unit/gapic/tasks_v2beta3/__init__.py
  tests/unit/gapic/tasks_v2beta3/test_cloud_tasks.py
Labels: api: cloudtasks, cla: yes, context: partial
