Repository googleapis/python-tasks, pull requests merged in 2021-04, with the labels that each got.

#86 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes, context: full

#87 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: cloudtasks, cla: yes, context: full, samples

#89 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudtasks, cla: yes

#94 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  synth.metadata
Labels: api: cloudtasks, automerge, cla: yes

#95 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudtasks, cla: yes
